name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-05"
compatibility_flags = [ "nodejs_compat" ]

[vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWU3NDI0YmMtZDE2NS00Y2RhLTljZTAtYTZmZWQ2MTQwYWMyIiwidGVuYW50X2lkIjoiMjgyZDgxZGEzOWE1YjI2MWJmODBjYjg1OGY2OGM5MTE1OGViMDg0YzFiMjE2ZDNiMzE4NmVmZjAxZDUyZDNhMyIsImludGVybmFsX3NlY3JldCI6IjQ2NGNmYjk2LTc3OWUtNDVkNC04NjkxLWY2YWI5NjY0ZTYzOSJ9.mRBK9i9hWUO57KXWsmqQYhSWaAOfvocrhxDhBlIG_M8"
 JWT_SECRET="Shalinium"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1